# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 419f2c3bae299c3b1bf3d3ef6dfeec611685f93a985b05775774443242bad0bc456c53dd58f959b741e762832125949a7cad5a6a97949f68e75723c282a2453a

test:
  secret_key_base: ab2cff4b1564c1d26113f572c5db1d89a0d1bf34344ba7d6cd38183fe518942345f2d6bcb940470777f5d4300371f8460c10e31a339e3dd7dc9bd382c3e5bff5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
